@startuml sequence
' 作者写一本书

Participant Client
Participant Singleton

Client -> Singleton: getInstance()
activate Singleton
Singleton -> Singleton : new Singleton()
Singleton --> Client : return Singleton
deactivate

@enduml