@startuml 结构图
interface Factory {
  +createProduct(): Product
}

class ConcreteFactory1  {
  +createProduct(): Product
}

class ConcreteFactory2  {
  +createProduct(): Product
}

interface Product {}

client -right-> Factory : 实例化、创建产品

Factory <|.down. ConcreteFactory1 : 实现
Factory <|.down. ConcreteFactory2 : 实现


ConcreteFactory1 --> Product : 实例化
ConcreteFactory1 --> ConcreteProduct1 : 实例化
Product <|.. ConcreteProduct1 : 实现

ConcreteFactory2 --> Product : 实例化
ConcreteFactory2 --> ConcreteProduct2 : 实例化
Product <|.. ConcreteProduct2 : 实现



@enduml